/*
 * crcany version 1.6, 10 February 2017
 *
 * Copyright (C) 2014, 2016, 2017 Mark Adler
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 * Mark Adler
 * madler@alumni.caltech.edu
 */

/*
 * Copyright 2014,2016,2017 Mark Adler
 * Copyright 2018 Didier Barvaux
 * Copyright 2018 Viveris Technologies
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

/**
 * @file   crcany.c
 * @brief  ROHC base CRC routines
 * @author Mark Adler <madler@alumni.caltech.edu>
 * @author Didier Barvaux <didier.barvaux@toulouse.viveris.com>
 * @author Didier Barvaux <didier@barvaux.org>
 *
 * This is a modified version of the CRC-3/ROHC algorithm initially
 * generated by crcany from Mark Adler (https://github.com/madler/crcany).
 */

#include "crcany.h"

// This code assumes that unsigned is 4 bytes.

#define table_byte table_word[0]

static unsigned char const table_word[][256] = {
   {0, 6, 1, 7, 2, 4, 3, 5, 4, 2, 5, 3, 6, 0, 7, 1, 5, 3, 4, 2, 7, 1, 6, 0, 1, 7,
    0, 6, 3, 5, 2, 4, 7, 1, 6, 0, 5, 3, 4, 2, 3, 5, 2, 4, 1, 7, 0, 6, 2, 4, 3, 5,
    0, 6, 1, 7, 6, 0, 7, 1, 4, 2, 5, 3, 3, 5, 2, 4, 1, 7, 0, 6, 7, 1, 6, 0, 5, 3,
    4, 2, 6, 0, 7, 1, 4, 2, 5, 3, 2, 4, 3, 5, 0, 6, 1, 7, 4, 2, 5, 3, 6, 0, 7, 1,
    0, 6, 1, 7, 2, 4, 3, 5, 1, 7, 0, 6, 3, 5, 2, 4, 5, 3, 4, 2, 7, 1, 6, 0, 6, 0,
    7, 1, 4, 2, 5, 3, 2, 4, 3, 5, 0, 6, 1, 7, 3, 5, 2, 4, 1, 7, 0, 6, 7, 1, 6, 0,
    5, 3, 4, 2, 1, 7, 0, 6, 3, 5, 2, 4, 5, 3, 4, 2, 7, 1, 6, 0, 4, 2, 5, 3, 6, 0,
    7, 1, 0, 6, 1, 7, 2, 4, 3, 5, 5, 3, 4, 2, 7, 1, 6, 0, 1, 7, 0, 6, 3, 5, 2, 4,
    0, 6, 1, 7, 2, 4, 3, 5, 4, 2, 5, 3, 6, 0, 7, 1, 2, 4, 3, 5, 0, 6, 1, 7, 6, 0,
    7, 1, 4, 2, 5, 3, 7, 1, 6, 0, 5, 3, 4, 2, 3, 5, 2, 4, 1, 7, 0, 6},
   {0, 3, 6, 5, 1, 2, 7, 4, 2, 1, 4, 7, 3, 0, 5, 6, 4, 7, 2, 1, 5, 6, 3, 0, 6, 5,
    0, 3, 7, 4, 1, 2, 5, 6, 3, 0, 4, 7, 2, 1, 7, 4, 1, 2, 6, 5, 0, 3, 1, 2, 7, 4,
    0, 3, 6, 5, 3, 0, 5, 6, 2, 1, 4, 7, 7, 4, 1, 2, 6, 5, 0, 3, 5, 6, 3, 0, 4, 7,
    2, 1, 3, 0, 5, 6, 2, 1, 4, 7, 1, 2, 7, 4, 0, 3, 6, 5, 2, 1, 4, 7, 3, 0, 5, 6,
    0, 3, 6, 5, 1, 2, 7, 4, 6, 5, 0, 3, 7, 4, 1, 2, 4, 7, 2, 1, 5, 6, 3, 0, 3, 0,
    5, 6, 2, 1, 4, 7, 1, 2, 7, 4, 0, 3, 6, 5, 7, 4, 1, 2, 6, 5, 0, 3, 5, 6, 3, 0,
    4, 7, 2, 1, 6, 5, 0, 3, 7, 4, 1, 2, 4, 7, 2, 1, 5, 6, 3, 0, 2, 1, 4, 7, 3, 0,
    5, 6, 0, 3, 6, 5, 1, 2, 7, 4, 4, 7, 2, 1, 5, 6, 3, 0, 6, 5, 0, 3, 7, 4, 1, 2,
    0, 3, 6, 5, 1, 2, 7, 4, 2, 1, 4, 7, 3, 0, 5, 6, 1, 2, 7, 4, 0, 3, 6, 5, 3, 0,
    5, 6, 2, 1, 4, 7, 5, 6, 3, 0, 4, 7, 2, 1, 7, 4, 1, 2, 6, 5, 0, 3},
   {0, 7, 3, 4, 6, 1, 5, 2, 1, 6, 2, 5, 7, 0, 4, 3, 2, 5, 1, 6, 4, 3, 7, 0, 3, 4,
    0, 7, 5, 2, 6, 1, 4, 3, 7, 0, 2, 5, 1, 6, 5, 2, 6, 1, 3, 4, 0, 7, 6, 1, 5, 2,
    0, 7, 3, 4, 7, 0, 4, 3, 1, 6, 2, 5, 5, 2, 6, 1, 3, 4, 0, 7, 4, 3, 7, 0, 2, 5,
    1, 6, 7, 0, 4, 3, 1, 6, 2, 5, 6, 1, 5, 2, 0, 7, 3, 4, 1, 6, 2, 5, 7, 0, 4, 3,
    0, 7, 3, 4, 6, 1, 5, 2, 3, 4, 0, 7, 5, 2, 6, 1, 2, 5, 1, 6, 4, 3, 7, 0, 7, 0,
    4, 3, 1, 6, 2, 5, 6, 1, 5, 2, 0, 7, 3, 4, 5, 2, 6, 1, 3, 4, 0, 7, 4, 3, 7, 0,
    2, 5, 1, 6, 3, 4, 0, 7, 5, 2, 6, 1, 2, 5, 1, 6, 4, 3, 7, 0, 1, 6, 2, 5, 7, 0,
    4, 3, 0, 7, 3, 4, 6, 1, 5, 2, 2, 5, 1, 6, 4, 3, 7, 0, 3, 4, 0, 7, 5, 2, 6, 1,
    0, 7, 3, 4, 6, 1, 5, 2, 1, 6, 2, 5, 7, 0, 4, 3, 6, 1, 5, 2, 0, 7, 3, 4, 7, 0,
    4, 3, 1, 6, 2, 5, 4, 3, 7, 0, 2, 5, 1, 6, 5, 2, 6, 1, 3, 4, 0, 7},
   {0, 5, 7, 2, 3, 6, 4, 1, 6, 3, 1, 4, 5, 0, 2, 7, 1, 4, 6, 3, 2, 7, 5, 0, 7, 2,
    0, 5, 4, 1, 3, 6, 2, 7, 5, 0, 1, 4, 6, 3, 4, 1, 3, 6, 7, 2, 0, 5, 3, 6, 4, 1,
    0, 5, 7, 2, 5, 0, 2, 7, 6, 3, 1, 4, 4, 1, 3, 6, 7, 2, 0, 5, 2, 7, 5, 0, 1, 4,
    6, 3, 5, 0, 2, 7, 6, 3, 1, 4, 3, 6, 4, 1, 0, 5, 7, 2, 6, 3, 1, 4, 5, 0, 2, 7,
    0, 5, 7, 2, 3, 6, 4, 1, 7, 2, 0, 5, 4, 1, 3, 6, 1, 4, 6, 3, 2, 7, 5, 0, 5, 0,
    2, 7, 6, 3, 1, 4, 3, 6, 4, 1, 0, 5, 7, 2, 4, 1, 3, 6, 7, 2, 0, 5, 2, 7, 5, 0,
    1, 4, 6, 3, 7, 2, 0, 5, 4, 1, 3, 6, 1, 4, 6, 3, 2, 7, 5, 0, 6, 3, 1, 4, 5, 0,
    2, 7, 0, 5, 7, 2, 3, 6, 4, 1, 1, 4, 6, 3, 2, 7, 5, 0, 7, 2, 0, 5, 4, 1, 3, 6,
    0, 5, 7, 2, 3, 6, 4, 1, 6, 3, 1, 4, 5, 0, 2, 7, 3, 6, 4, 1, 0, 5, 7, 2, 5, 0,
    2, 7, 6, 3, 1, 4, 2, 7, 5, 0, 1, 4, 6, 3, 4, 1, 3, 6, 7, 2, 0, 5},
   {0, 4, 5, 1, 7, 3, 2, 6, 3, 7, 6, 2, 4, 0, 1, 5, 6, 2, 3, 7, 1, 5, 4, 0, 5, 1,
    0, 4, 2, 6, 7, 3, 1, 5, 4, 0, 6, 2, 3, 7, 2, 6, 7, 3, 5, 1, 0, 4, 7, 3, 2, 6,
    0, 4, 5, 1, 4, 0, 1, 5, 3, 7, 6, 2, 2, 6, 7, 3, 5, 1, 0, 4, 1, 5, 4, 0, 6, 2,
    3, 7, 4, 0, 1, 5, 3, 7, 6, 2, 7, 3, 2, 6, 0, 4, 5, 1, 3, 7, 6, 2, 4, 0, 1, 5,
    0, 4, 5, 1, 7, 3, 2, 6, 5, 1, 0, 4, 2, 6, 7, 3, 6, 2, 3, 7, 1, 5, 4, 0, 4, 0,
    1, 5, 3, 7, 6, 2, 7, 3, 2, 6, 0, 4, 5, 1, 2, 6, 7, 3, 5, 1, 0, 4, 1, 5, 4, 0,
    6, 2, 3, 7, 5, 1, 0, 4, 2, 6, 7, 3, 6, 2, 3, 7, 1, 5, 4, 0, 3, 7, 6, 2, 4, 0,
    1, 5, 0, 4, 5, 1, 7, 3, 2, 6, 6, 2, 3, 7, 1, 5, 4, 0, 5, 1, 0, 4, 2, 6, 7, 3,
    0, 4, 5, 1, 7, 3, 2, 6, 3, 7, 6, 2, 4, 0, 1, 5, 7, 3, 2, 6, 0, 4, 5, 1, 4, 0,
    1, 5, 3, 7, 6, 2, 1, 5, 4, 0, 6, 2, 3, 7, 2, 6, 7, 3, 5, 1, 0, 4},
   {0, 2, 4, 6, 5, 7, 1, 3, 7, 5, 3, 1, 2, 0, 6, 4, 3, 1, 7, 5, 6, 4, 2, 0, 4, 6,
    0, 2, 1, 3, 5, 7, 6, 4, 2, 0, 3, 1, 7, 5, 1, 3, 5, 7, 4, 6, 0, 2, 5, 7, 1, 3,
    0, 2, 4, 6, 2, 0, 6, 4, 7, 5, 3, 1, 1, 3, 5, 7, 4, 6, 0, 2, 6, 4, 2, 0, 3, 1,
    7, 5, 2, 0, 6, 4, 7, 5, 3, 1, 5, 7, 1, 3, 0, 2, 4, 6, 7, 5, 3, 1, 2, 0, 6, 4,
    0, 2, 4, 6, 5, 7, 1, 3, 4, 6, 0, 2, 1, 3, 5, 7, 3, 1, 7, 5, 6, 4, 2, 0, 2, 0,
    6, 4, 7, 5, 3, 1, 5, 7, 1, 3, 0, 2, 4, 6, 1, 3, 5, 7, 4, 6, 0, 2, 6, 4, 2, 0,
    3, 1, 7, 5, 4, 6, 0, 2, 1, 3, 5, 7, 3, 1, 7, 5, 6, 4, 2, 0, 7, 5, 3, 1, 2, 0,
    6, 4, 0, 2, 4, 6, 5, 7, 1, 3, 3, 1, 7, 5, 6, 4, 2, 0, 4, 6, 0, 2, 1, 3, 5, 7,
    0, 2, 4, 6, 5, 7, 1, 3, 7, 5, 3, 1, 2, 0, 6, 4, 5, 7, 1, 3, 0, 2, 4, 6, 2, 0,
    6, 4, 7, 5, 3, 1, 6, 4, 2, 0, 3, 1, 7, 5, 1, 3, 5, 7, 4, 6, 0, 2},
   {0, 1, 2, 3, 4, 5, 6, 7, 5, 4, 7, 6, 1, 0, 3, 2, 7, 6, 5, 4, 3, 2, 1, 0, 2, 3,
    0, 1, 6, 7, 4, 5, 3, 2, 1, 0, 7, 6, 5, 4, 6, 7, 4, 5, 2, 3, 0, 1, 4, 5, 6, 7,
    0, 1, 2, 3, 1, 0, 3, 2, 5, 4, 7, 6, 6, 7, 4, 5, 2, 3, 0, 1, 3, 2, 1, 0, 7, 6,
    5, 4, 1, 0, 3, 2, 5, 4, 7, 6, 4, 5, 6, 7, 0, 1, 2, 3, 5, 4, 7, 6, 1, 0, 3, 2,
    0, 1, 2, 3, 4, 5, 6, 7, 2, 3, 0, 1, 6, 7, 4, 5, 7, 6, 5, 4, 3, 2, 1, 0, 1, 0,
    3, 2, 5, 4, 7, 6, 4, 5, 6, 7, 0, 1, 2, 3, 6, 7, 4, 5, 2, 3, 0, 1, 3, 2, 1, 0,
    7, 6, 5, 4, 2, 3, 0, 1, 6, 7, 4, 5, 7, 6, 5, 4, 3, 2, 1, 0, 5, 4, 7, 6, 1, 0,
    3, 2, 0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0, 2, 3, 0, 1, 6, 7, 4, 5,
    0, 1, 2, 3, 4, 5, 6, 7, 5, 4, 7, 6, 1, 0, 3, 2, 4, 5, 6, 7, 0, 1, 2, 3, 1, 0,
    3, 2, 5, 4, 7, 6, 3, 2, 1, 0, 7, 6, 5, 4, 6, 7, 4, 5, 2, 3, 0, 1},
   {0, 6, 1, 7, 2, 4, 3, 5, 4, 2, 5, 3, 6, 0, 7, 1, 5, 3, 4, 2, 7, 1, 6, 0, 1, 7,
    0, 6, 3, 5, 2, 4, 7, 1, 6, 0, 5, 3, 4, 2, 3, 5, 2, 4, 1, 7, 0, 6, 2, 4, 3, 5,
    0, 6, 1, 7, 6, 0, 7, 1, 4, 2, 5, 3, 3, 5, 2, 4, 1, 7, 0, 6, 7, 1, 6, 0, 5, 3,
    4, 2, 6, 0, 7, 1, 4, 2, 5, 3, 2, 4, 3, 5, 0, 6, 1, 7, 4, 2, 5, 3, 6, 0, 7, 1,
    0, 6, 1, 7, 2, 4, 3, 5, 1, 7, 0, 6, 3, 5, 2, 4, 5, 3, 4, 2, 7, 1, 6, 0, 6, 0,
    7, 1, 4, 2, 5, 3, 2, 4, 3, 5, 0, 6, 1, 7, 3, 5, 2, 4, 1, 7, 0, 6, 7, 1, 6, 0,
    5, 3, 4, 2, 1, 7, 0, 6, 3, 5, 2, 4, 5, 3, 4, 2, 7, 1, 6, 0, 4, 2, 5, 3, 6, 0,
    7, 1, 0, 6, 1, 7, 2, 4, 3, 5, 5, 3, 4, 2, 7, 1, 6, 0, 1, 7, 0, 6, 3, 5, 2, 4,
    0, 6, 1, 7, 2, 4, 3, 5, 4, 2, 5, 3, 6, 0, 7, 1, 2, 4, 3, 5, 0, 6, 1, 7, 6, 0,
    7, 1, 4, 2, 5, 3, 7, 1, 6, 0, 5, 3, 4, 2, 3, 5, 2, 4, 1, 7, 0, 6}
};

// This code assumes that integers are stored little-endian.

unsigned crc3rohc_word(unsigned crc, void const *mem, size_t len)
{
	unsigned char const* data = mem;

	crc &= 0x7;
	while(len && ((ptrdiff_t)data & 0x7))
	{
		crc = table_byte[crc ^ *data++];
		len--;
	}
	if(len >= 8)
	{
		do
		{
			uintmax_t word = crc ^ *(uintmax_t const *)data;
			crc = table_word[7][word & 0xff] ^
			      table_word[6][(word >> 8) & 0xff] ^
			      table_word[5][(word >> 16) & 0xff] ^
			      table_word[4][(word >> 24) & 0xff] ^
			      table_word[3][(word >> 32) & 0xff] ^
			      table_word[2][(word >> 40) & 0xff] ^
			      table_word[1][(word >> 48) & 0xff] ^
			      table_word[0][word >> 56];
			data += 8;
			len -= 8;
		}
		while(len >= 8);
	}

	while(len--)
	{
		crc = table_byte[crc ^ *data++];
	}

	return crc;
}

