/*
 * crcany version 1.6, 10 February 2017
 *
 * Copyright (C) 2014, 2016, 2017 Mark Adler
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 * Mark Adler
 * madler@alumni.caltech.edu
 */

/*
 * Copyright 2014,2016,2017 Mark Adler
 * Copyright 2018 Didier Barvaux
 * Copyright 2018 Viveris Technologies
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

/**
 * @file   crcany.h
 * @brief  ROHC base CRC routines
 * @author Mark Adler <madler@alumni.caltech.edu>
 * @author Didier Barvaux <didier.barvaux@toulouse.viveris.com>
 * @author Didier Barvaux <didier@barvaux.org>
 *
 * This is a modified version of the CRC-3/ROHC algorithm initially
 * generated by crcany from Mark Adler (https://github.com/madler/crcany).
 */

#ifndef ROHC_COMMON_CRCANY_H
#define ROHC_COMMON_CRCANY_H

#include <stddef.h>
#include <stdint.h>

// Compute the CRC a word at a time.
unsigned crc3rohc_word(unsigned crc, void const *mem, size_t len)
	__attribute__((warn_unused_result, nonnull(2)));

#endif

